import Navbar from './components/Navbar'
import './globals.css'
import {  Oswald } from 'next/font/google'

const wald = Oswald({ 
  subsets: ['latin'],
  weight: ['500']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function layout({ children }) {
  return (
    <html lang="en">
      <body className={wald.className}>
        <Navbar/>
        {children}</body>
    </html>
  )
}
